// src/App.tsx
import React, { useState } from 'react';
import { Package2, Calendar, AlertCircle, Plus, Search, Trash2 } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { ptBR } from 'date-fns/locale';

interface Product {
  id: string;
  name: string;
  openingDate: string;
  expirationDate: string;
  notes: string;
}

function App() {
  const [products, setProducts] = useState<Product[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [search, setSearch] = useState('');

  const addProduct = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const formData = new FormData(form);
    
    const newProduct = {
      id: crypto.randomUUID(),
      name: formData.get('name') as string,
      openingDate: formData.get('openingDate') as string,
      expirationDate: formData.get('expirationDate') as string,
      notes: formData.get('notes') as string,
    };

    setProducts([...products, newProduct]);
    setShowForm(false);
    form.reset();
  };

  const deleteProduct = (id: string) => {
    setProducts(products.filter(p => p.id !== id));
  };

  const filteredProducts = products.filter(p => 
    p.name.toLowerCase().includes(search.toLowerCase())
  );

  const isExpiringSoon = (date: string) => {
    const days = Math.ceil((new Date(date).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24));
    return days <= 7 && days > 0;
  };

  const isExpired = (date: string) => {
    return new Date(date) < new Date();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50">
      <div className="max-w-6xl mx-auto p-6">
        <header className="mb-8">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Package2 className="w-8 h-8 text-indigo-600" />
              <h1 className="text-2xl font-bold text-gray-800">Controle de Produtos</h1>
            </div>
            <button
              onClick={() => setShowForm(true)}
              className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition-colors"
            >
              <Plus className="w-4 h-4" />
              Novo Produto
            </button>
          </div>
        </header>

        {showForm && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-lg p-6 w-full max-w-md">
              <h2 className="text-xl font-semibold mb-4">Adicionar Novo Produto</h2>
              <form onSubmit={addProduct} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700">Nome do Produto</label>
                  <input
                    required
                    type="text"
                    name="name"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Data de Abertura</label>
                  <input
                    required
                    type="date"
                    name="openingDate"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Data de Vencimento</label>
                  <input
                    required
                    type="date"
                    name="expirationDate"
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700">Observações</label>
                  <textarea
                    name="notes"
                    rows={3}
                    className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
                  ></textarea>
                </div>
                <div className="flex gap-3 justify-end">
                  <button
                    type="button"
                    onClick={() => setShowForm(false)}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200"
                  >
                    Cancelar
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700"
                  >
                    Salvar
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}

        <div className="mb-6">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
            <input
              type="text"
              placeholder="Buscar produtos..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="pl-10 pr-4 py-2 w-full rounded-lg border border-gray-200 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
            />
          </div>
        </div>

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {filteredProducts.map((product) => (
            <div
              key={product.id}
              className={`bg-white rounded-lg shadow-sm p-6 border-l-4 ${
                isExpired(product.expirationDate)
                  ? 'border-red-500'
                  : isExpiringSoon(product.expirationDate)
                  ? 'border-yellow-500'
                  : 'border-green-500'
              }`}
            >
              <div className="flex justify-between items-start mb-4">
                <h3 className="font-semibold text-lg text-gray-800">{product.name}</h3>
                <button
                  onClick={() => deleteProduct(product.id)}
                  className="text-gray-400 hover:text-red-500 transition-colors"
                >
                  <Trash2 className="w-5 h-5" />
                </button>
              </div>
              
              <div className="space-y-2 text-sm">
                <div className="flex items-center gap-2 text-gray-600">
                  <Calendar className="w-4 h-4" />
                  <span>Aberto em: {new Date(product.openingDate).toLocaleDateString('pt-BR')}</span>
                </div>
                <div className="flex items-center gap-2">
                  <AlertCircle className="w-4 h-4" />
                  <span className={`${
                    isExpired(product.expirationDate)
                      ? 'text-red-600'
                      : isExpiringSoon(product.expirationDate)
                      ? 'text-yellow-600'
                      : 'text-green-600'
                  }`}>
                    Vence {formatDistanceToNow(new Date(product.expirationDate), { locale: ptBR, addSuffix: true })}
                  </span>
                </div>
                {product.notes && (
                  <p className="text-gray-600 mt-2 italic">
                    {product.notes}
                  </p>
                )}
              </div>
            </div>
          ))}
        </div>

        {filteredProducts.length === 0 && (
          <div className="text-center py-12">
            <Package2 className="w-12 h-12 text-gray-400 mx-auto mb-4" />
            <p className="text-gray-500">Nenhum produto encontrado</p>
          </div>
        )}
      </div>
    </div>
  );
}

export default App;

// app/App.svelte
{#if showForm}
  <GridLayout rows="*" columns="*" class="modal">
    <StackLayout class="form" row="0" col="0">
      <Label text="Adicionar Novo Produto" class="title" />
      <TextField bind:text={newProduct.name} hint="Nome do Produto" class="input" />
      <DatePicker bind:date={newProduct.openingDate} class="input" />
      <DatePicker bind:date={newProduct.expirationDate} class="input" />
      <TextView bind:text={newProduct.notes} hint="Observações" class="input" rows="3" />
      <FlexboxLayout class="button-row">
        <Button text="Cancelar" on:tap={() => showForm = false} class="btn-secondary" />
        <Button text="Salvar" on:tap={addProduct} class="btn-primary" />
      </FlexboxLayout>
    </StackLayout>
  </GridLayout>
{/if}

<ActionBar title="Controle de Produtos">
  <ActionItem on:tap={() => showForm = true} ios.position="right" android.position="actionBar">
    <Label text="+" class="action-item" />
  </ActionItem>
</ActionBar>

<GridLayout rows="auto, *">
  <SearchBar row="0" hint="Buscar produtos..." bind:text={searchText} />
  
  <ListView row="1" items={filteredProducts} class="list-group">
    <Template let:item>
      <GridLayout columns="*, auto" rows="auto, auto, auto" class="list-group-item">
        <Label col="0" row="0" text={item.name} class="product-name" />
        <Label col="0" row="1" text={`Aberto em: ${formatDate(item.openingDate)}`} class="date" />
        <Label col="0" row="2" text={getExpirationText(item.expirationDate)} class={getExpirationClass(item.expirationDate)} />
        {#if item.notes}
          <Label col="0" row="3" text={item.notes} class="notes" textWrap="true" />
        {/if}
        <Button col="1" row="0" text="×" on:tap={() => deleteProduct(item.id)} class="delete-btn" />
      </GridLayout>
    </Template>
  </ListView>
</GridLayout>

<script lang="typescript">
  import { formatDistanceToNow } from 'date-fns'
  import { ptBR } from 'date-fns/locale'
  
  let products = []
  let showForm = false
  let searchText = ''
  
  let newProduct = {
    name: '',
    openingDate: new Date(),
    expirationDate: new Date(),
    notes: ''
  }
  
  $: filteredProducts = products.filter(p => 
    p.name.toLowerCase().includes(searchText.toLowerCase())
  )
  
  function addProduct() {
    products = [...products, {
      id: Date.now().toString(),
      ...newProduct
    }]
    showForm = false
    newProduct = {
      name: '',
      openingDate: new Date(),
      expirationDate: new Date(),
      notes: ''
    }
  }
  
  function deleteProduct(id) {
    products = products.filter(p => p.id !== id)
  }
  
  function formatDate(date) {
    return new Date(date).toLocaleDateString('pt-BR')
  }
  
  function isExpiringSoon(date) {
    const days = Math.ceil((new Date(date).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))
    return days <= 7 && days > 0
  }
  
  function isExpired(date) {
    return new Date(date) < new Date()
  }
  
  function getExpirationText(date) {
    return `Vence ${formatDistanceToNow(new Date(date), { locale: ptBR, addSuffix: true })}`
  }
  
  function getExpirationClass(date) {
    return isExpired(date) 
      ? 'expired' 
      : isExpiringSoon(date) 
        ? 'expiring-soon' 
        : 'valid'
  }
</script>

<style>
  .modal {
    background-color: rgba(0, 0, 0, 0.5);
  }
  
  .form {
    background-color: white;
    padding: 20;
    border-radius: 10;
    width: 80%;
    vertical-align: middle;
  }
  
  .title {
    font-size: 20;
    font-weight: bold;
    margin-bottom: 15;
  }
  
  .input {
    margin-bottom: 15;
  }
  
  .button-row {
    justify-content: flex-end;
    gap: 10;
  }
  
  .btn-primary {
    background-color: #4f46e5;
    color: white;
  }
  
  .btn-secondary {
    background-color: #e5e7eb;
  }
  
  .product-name {
    font-size: 18;
    font-weight: bold;
  }
  
  .date {
    font-size: 14;
    color: #666;
  }
  
  .expired {
    color: #dc2626;
  }
  
  .expiring-soon {
    color: #d97706;
  }
  
  .valid {
    color: #059669;
  }
  
  .notes {
    font-style: italic;
    color: #666;
    margin-top: 5;
  }
  
  .delete-btn {
    font-size: 20;
    background-color: transparent;
    color: #dc2626;
    width: 40;
    height: 40;
    padding: 0;
  }
  
  .action-item {
    font-size: 24;
    font-weight: bold;
    color: white;
    margin-right: 10;
  }
</style>
